apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
        - name: mail-service
          image: ghcr.io/goal651/springboot_microservice/mail-service:latest
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 40
            periodSeconds: 10
