FROM maven:3.9.6-eclipse-temurin-21 AS DEV

# Set working directory inside the container
WORKDIR /app

# Copy pom.xml and download dependencies first (cached layer)
COPY pom.xml .
RUN mvn dependency:go-offline 

# Copy the rest of your source code
COPY src ./src

# Run the app
CMD ["mvn", "spring-boot:run"]