eureka.client.service-url.defaultZone=http://eureka:8761/eureka
spring.kafka.bootstrap-servers=kafka:29092
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.server.port=${MANAGEMENT_PORT}
management.tracing.sampling.probability=1.0 
# 1.0 for dev and testing, adjust for production like 0.1 or 0.01 to reduce overhead
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans